version: "3.8"

services:
  bittrack:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: BitTrack
    command: node BitTrack.js
    restart: unless-stopped
    ports:
      - "8585:8585"
    volumes:
      - data:/app/data
    environment:
      DATA_DIR: "/app/data"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  data:
    driver: local